### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=WebStorm
### POST request to example server
POST http://localhost:3000/user/login
Content-Type: application/json
{
    "email": "demo12@gmail.com",
    "password": "123456"
}
